# Generated by Django 3.1.5 on 2021-01-21 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_days', models.PositiveIntegerField(help_text='Number of days employee is entitled to per annum', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_carry_over', models.PositiveIntegerField(default=0, help_text='Number of days an employee can carry over from one year to the next.')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_taken', models.IntegerField(default=0)),
                ('leave_balance', models.FloatField(editable=False)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Running'), (3, 'Returned'), (4, 'Cancelled'), (5, 'Rejected')], default=0, editable=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('handover_note', models.FileField(blank=True, help_text='Upload a document containing handover instructions', null=True, upload_to=leave.models.get_employee_hon_upload_path)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavepolicy')),
                ('relief', models.ForeignKey(blank=True, help_text='Notice will be sent to your relief', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relief_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leave',
                'ordering': ('-id',),
                'permissions': (('can_approve_leave', 'Can approve leave'), ('can_manage_leave', 'Can manage leave')),
            },
        ),
    ]
