# Generated by Django 3.1.5 on 2021-01-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leave', '0002_leavepolicy_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='relief',
            field=models.ForeignKey(blank=True, help_text='Notice will be sent to your relief', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relief_leaves', to='employees.employee'),
        ),
    ]
